export const UNAUTHORIZED_ERROR = 'UNAUTHORIZED_ERROR';
export const UNKNOWN_ERROR = 'UNKNOWN_ERROR';
export const INVALID_USERNAME_OR_PASSWORD = 'INVALID_USERNAME_OR_PASSWORD';
export const RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND';
export const RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS';
