export const config = {
  "label": "@@@label",
  "name": "Slider",
  "icon": 'radix-icons:slider',
  "importCode": ["import { Slider } from 'ui-lib';", "import funs from 'funs';"],
  "locales": {
    "cn": {
      "label": "滑块",
      "small": "小",
      "medium": "中",
      "large": "大",
      "defaultValue": "默认值",
      "readOnly": "只读",
      "size": "尺寸",
      "max": "最大值",
      "min": "最小值",
      "valueLabelDisplay": "值标签显示",
      "auto": "悬停时显示",
      "off": "始终隐藏",
      "on": "始终显示",
      "orientation": "方向",
      "horizontal": "水平",
      "vertical": "垂直",
    },
    "en": {
      "label": "Slider",
      "small": "Small",
      "medium": "Medium",
      "large": "Large",
      "defaultValue": "Default Value",
      "readOnly": "Read Only",
      "size": "Size",
      "max": "Max",
      "min": "Min",
      "valueLabelDisplay": "Value Label Display",
      "auto": "Disaply on hovered",
      "off": "Always hide",
      "on": "Always show",
      "orientation": "Orientation",
      "horizontal": "Horizontal",
      "vertical": "Vertical",
    }
  }
}
